//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clases
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Data.SqlClient;
    using System.ComponentModel;
    
    public partial class C_Cliente
    {
        conexion con;
        public C_Cliente()
        {
            this.C_Cita = new HashSet<C_Cita>();
        }
    // Cliente
        public int id_cliente { get; set; }
        public Nullable<int> id_td { get; set; }
        public string documento_identidad { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public Nullable<int> id_pais { get; set; }
        public string direccion { get; set; }
        public string t_habitacion { get; set; }
        public string t_celular { get; set; }
        public string t_oficina { get; set; }
        public Nullable<int> id_status { get; set; }
        public Nullable<int> id_locacion { get; set; }
        public string correo { get; set; }
        public string profesion { get; set; }
        public Nullable<int> edad { get; set; }
        public string edo_civil { get; set; }
        public Nullable<System.DateTime> f_nacimiento { get; set; }
    
        public virtual ICollection<C_Cita> C_Cita { get; set; }
        public virtual C_Locacion C_Locacion { get; set; }
        public virtual C_Pais C_Pais { get; set; }
        public virtual C_Status C_Status { get; set; }
        public virtual C_TipoDocumento C_TipoDocumento { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string promotor { get; set; }
        public Nullable<int> idPromotor { get; set; }
       
        public string observacion { get; set; }
       
        public Nullable<int> asignado { get; set; }
        public bool asig { get; set; }
        public bool IsSelected { get { return asig; } set { asig = value; OnChanged("IsSelected"); } }
        public int Id_statusPrincipal { get; set; }
        public Nullable<int> Id_subStatusCita { get; set; }
        public string statusPrinc { get; set; }
       
        // Acompañante
        public Nullable<int> id_tdA { get; set; }
        public string documento_identidadA { get; set; }
        public string nombreA { get; set; }
        public string apellidoA { get; set; }
        public string correoA { get; set; }
        public string profesionA { get; set; }
        public Nullable<int> edadA { get; set; }
        public string telefonoA { get; set; }

        //Asignacion
        public DateTime fechaAsig { get; set; }


        //Asignacion confirmador
        public DateTime fechaSigCon { get; set; }
        public string ola{ get; set; }

        //Verifica edicion de datos

        public int? editando { get; set; }


        public List<C_Cliente> listarCLientes()
        {
            List<C_Cliente> clientes = new List<C_Cliente>();
            if (con == null)
                con = new conexion();
            con.conectar();
            SqlCommand cmd = new SqlCommand("_sp_listarClientes", con.cnxn);
            cmd.CommandType = CommandType.StoredProcedure;
            SqlDataReader dr = cmd.ExecuteReader();
            if (dr.HasRows)
            {
                while (dr.Read())
                {
                    if (dr.GetInt32(17) != 4)
                    {
                        C_Cliente client = new C_Cliente();
                        client.id_cliente = dr.GetInt32(0);
                        client.documento_identidad = (dr["documento_identidad"].Equals(null) ? null : dr["documento_identidad"].ToString().Trim(new char[] { ' ' }));
                        client.nombre = dr.GetString(2).Trim(new char[] { ' ' });
                        client.apellido = dr.GetString(3).Trim(new char[] { ' ' });
                        client.direccion = (dr["direccion"].Equals(null) ? null : dr["direccion"].ToString().Trim(new char[] { ' ' }));
                        client.correo = (dr["correo"].Equals(null) ? null : dr["correo"].ToString().Trim(new char[] { ' ' }));
                        client.C_TipoDocumento = new Clases.C_TipoDocumento();
                        client.C_TipoDocumento.descripcion = (dr["tipoDoc"].Equals(null) ? null : dr["tipoDoc"].ToString().Trim(new char[] { ' ' }));
                        client.C_Status = new Clases.C_Status();
                        client.C_Status.descripcion = dr.GetString(7).Trim(new char[] { ' ' });
                        client.edo_civil = (dr["edo_civil"].Equals(null) ? null : dr["edo_civil"].ToString().Trim(new char[] { ' ' }));
                        client.edad = (Convert.IsDBNull(dr["edad"]) ? null : (int?)Convert.ToInt32(dr["edad"]));
                        //client.f_nacimiento = (dr["f_nacimiento"].Equals(null) ? null : (DateTime?)Convert.ToDateTime(dr["f_nacimiento"])); 
                        client.C_Locacion = new Clases.C_Locacion();
                        client.C_Locacion.codigo = (dr["locacion"].Equals(null) ? null : dr["locacion"].ToString().Trim(new char[] { ' ' }));
                        client.C_Pais = new Clases.C_Pais();
                        client.C_Pais.nombre = (dr["pais"].Equals(null) ? null : dr["pais"].ToString().Trim(new char[] { ' ' }));
                        client.profesion = (dr["profesion"].Equals(null) ? null : dr["profesion"].ToString().Trim(new char[] { ' ' }));
                        client.t_celular = (dr["t_celular"].Equals(null) ? null : dr["t_celular"].ToString().Trim(new char[] { ' ' }));
                        client.t_habitacion = (dr["t_habitacion"].Equals(null) ? null : dr["t_habitacion"].ToString().Trim(new char[] { ' ' }));
                        client.t_oficina = (dr["t_oficina"].Equals(null) ? null : dr["t_oficina"].ToString().Trim(new char[] { ' ' })); 
                        client.id_status = dr.GetInt32(17);
                        client.id_locacion = (Convert.IsDBNull(dr["id_locacion"]) ? null : (int?)Convert.ToInt32(dr["id_locacion"]));
                        client.id_pais = (Convert.IsDBNull(dr["id_pais"]) ? null : (int?)Convert.ToInt32(dr["id_pais"])); 
                        client.id_td = (Convert.IsDBNull(dr.GetInt32(20)) ? null : (int?)Convert.ToInt32(dr.GetInt32(20))); 
                        DateTime? f = (Convert.IsDBNull(dr["f_nacimiento"]) ? null : (DateTime?)Convert.ToDateTime(dr["f_nacimiento"]));
                        client.f_nacimiento = f;
                        client.asignado = dr.GetInt32(21);
                        client.Id_statusPrincipal = dr.GetInt32(22);
                        client.Id_subStatusCita = (Convert.IsDBNull(dr["statusCita"]) ? null : (int?)Convert.ToInt32(dr["statusCita"]));
                        client.observacion = (dr["observacion"].Equals(null) ? null : dr["observacion"].ToString().Trim(new char[] { ' ' }));
                        client.id_tdA = (Convert.IsDBNull(dr["Expr1"]) ? null : (int?)Convert.ToInt32(dr["Expr1"]));
                        client.documento_identidadA = (dr["Expr2"].Equals(null) ? null : dr["Expr2"].ToString().Trim(new char[] { ' ' }));
                        client.nombreA = (dr["Expr3"].Equals(null) ? null : dr["Expr3"].ToString().Trim(new char[] { ' ' }));
                        client.apellidoA = (dr["Expr4"].Equals(null) ? null : dr["Expr4"].ToString().Trim(new char[] { ' ' }));
                        client.edadA = (Convert.IsDBNull(dr["Expr5"]) ? null : (int?)Convert.ToInt32(dr["Expr5"]));
                        client.profesionA = (dr["ocupacion"].Equals(null) ? null : dr["ocupacion"].ToString().Trim(new char[] { ' ' }));
                        client.telefonoA = (dr["telefono"].Equals(null) ? null : dr["telefono"].ToString().Trim(new char[] { ' ' }));
                        client.correoA = (dr["Expr6"].Equals(null) ? null : dr["Expr6"].ToString().Trim(new char[] { ' ' }));
                        client.statusPrinc = dr.GetString(33).Trim(new char[] { ' ' });
                        client.idPromotor = (Convert.IsDBNull(dr["idPromotor"]) ? null : (int?)Convert.ToInt32(dr["idPromotor"]));
                        client.editando = (Convert.IsDBNull(dr["editando"]) ? null : (int?)Convert.ToInt32(dr["editando"]));
                        clientes.Add(client);
                    }
                }
            }
            con.desconectar();
            return clientes;
        }
        public List<C_Cliente> listarAfiliados()
        {
            List<C_Cliente> clientes = new List<C_Cliente>();
            if (con == null)
                con = new conexion();
            con.conectar();
            SqlCommand cmd = new SqlCommand("_sp_listarClientes", con.cnxn);
            cmd.CommandType = CommandType.StoredProcedure;
            SqlDataReader dr = cmd.ExecuteReader();
            if (dr.HasRows)
            {
                while (dr.Read())
                {
                    if (dr.GetInt32(17) == 4)
                    {
                        C_Cliente client = new C_Cliente();
                        client.id_cliente = dr.GetInt32(0);
                        client.documento_identidad = (dr["documento_identidad"].Equals(null) ? null : dr["documento_identidad"].ToString().Trim(new char[] { ' ' }));
                        client.nombre = dr.GetString(2).Trim(new char[] { ' ' });
                        client.apellido = dr.GetString(3).Trim(new char[] { ' ' });
                        client.direccion = (dr["direccion"].Equals(null) ? null : dr["direccion"].ToString().Trim(new char[] { ' ' }));
                        client.correo = (dr["correo"].Equals(null) ? null : dr["correo"].ToString().Trim(new char[] { ' ' }));
                        client.C_TipoDocumento = new Clases.C_TipoDocumento();
                        client.C_TipoDocumento.descripcion = (dr["tipoDoc"].Equals(null) ? null : dr["tipoDoc"].ToString().Trim(new char[] { ' ' }));
                        client.C_Status = new Clases.C_Status();
                        client.C_Status.descripcion = dr.GetString(7).Trim(new char[] { ' ' });
                        client.edo_civil = (dr["edo_civil"].Equals(null) ? null : dr["edo_civil"].ToString().Trim(new char[] { ' ' }));
                        client.edad = (Convert.IsDBNull(dr["edad"]) ? null : (int?)Convert.ToInt32(dr["edad"]));
                        //client.f_nacimiento = (dr["f_nacimiento"].Equals(null) ? null : (DateTime?)Convert.ToDateTime(dr["f_nacimiento"])); 
                        client.C_Locacion = new Clases.C_Locacion();
                        client.C_Locacion.codigo = (dr["locacion"].Equals(null) ? null : dr["locacion"].ToString().Trim(new char[] { ' ' }));
                        client.C_Pais = new Clases.C_Pais();
                        client.C_Pais.nombre = (dr["pais"].Equals(null) ? null : dr["pais"].ToString().Trim(new char[] { ' ' }));
                        client.profesion = (dr["profesion"].Equals(null) ? null : dr["profesion"].ToString().Trim(new char[] { ' ' }));
                        client.t_celular = (dr["t_celular"].Equals(null) ? null : dr["t_celular"].ToString().Trim(new char[] { ' ' }));
                        client.t_habitacion = (dr["t_habitacion"].Equals(null) ? null : dr["t_habitacion"].ToString().Trim(new char[] { ' ' }));
                        client.t_oficina = (dr["t_oficina"].Equals(null) ? null : dr["t_oficina"].ToString().Trim(new char[] { ' ' })); 
                        client.id_status = dr.GetInt32(17);
                        client.id_locacion = (Convert.IsDBNull(dr["id_locacion"]) ? null : (int?)Convert.ToInt32(dr["id_locacion"]));
                        client.id_pais = (Convert.IsDBNull(dr["id_pais"]) ? null : (int?)Convert.ToInt32(dr["id_pais"])); 
                        client.id_td = (Convert.IsDBNull(dr.GetInt32(20)) ? null : (int?)Convert.ToInt32(dr.GetInt32(20))); 
                        client.asignado = dr.GetInt32(21);
                        client.Id_statusPrincipal = dr.GetInt32(22);
                        client.Id_subStatusCita = (Convert.IsDBNull(dr["statusCita"]) ? null : (int?)Convert.ToInt32(dr["statusCita"]));
                        client.observacion = (dr["observacion"].Equals(null) ? null : dr["observacion"].ToString().Trim(new char[] { ' ' }));
                        client.id_tdA = (Convert.IsDBNull(dr["Expr1"]) ? null : (int?)Convert.ToInt32(dr["Expr1"]));
                        client.documento_identidadA = (dr["Expr2"].Equals(null) ? null : dr["Expr2"].ToString().Trim(new char[] { ' ' }));
                        client.nombreA = (dr["Expr3"].Equals(null) ? null : dr["Expr3"].ToString().Trim(new char[] { ' ' }));
                        client.apellidoA = (dr["Expr4"].Equals(null) ? null : dr["Expr4"].ToString().Trim(new char[] { ' ' }));
                        client.edadA = (Convert.IsDBNull(dr["Expr5"]) ? null : (int?)Convert.ToInt32(dr["Expr5"]));
                        client.profesionA = (dr["ocupacion"].Equals(null) ? null : dr["ocupacion"].ToString().Trim(new char[] { ' ' }));
                        client.telefonoA = (dr["telefono"].Equals(null) ? null : dr["telefono"].ToString().Trim(new char[] { ' ' }));
                        client.correoA = (dr["Expr6"].Equals(null) ? null : dr["Expr6"].ToString().Trim(new char[] { ' ' }));
                        client.statusPrinc = dr.GetString(33).Trim(new char[] { ' ' });
                        client.idPromotor = (Convert.IsDBNull(dr["idPromotor"]) ? null : (int?)Convert.ToInt32(dr["idPromotor"]));
                        client.editando = (Convert.IsDBNull(dr["editando"]) ? null : (int?)Convert.ToInt32(dr["editando"]));
                        clientes.Add(client);
                    }
                }
            }
            con.desconectar();
            return clientes;
        }

        public List<C_Cliente> listarParaConfirmar(int cantidad,string ola,DateTime? fecha)
        {
            List<C_Cliente> clientes = new List<C_Cliente>();
            if (con == null)
                con = new conexion();
            con.conectar();
            SqlCommand cmd = new SqlCommand("_sp_listarProsCon", con.cnxn);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@cantidad", cantidad);
            cmd.Parameters.AddWithValue("@ola", ola);
            cmd.Parameters.AddWithValue("@fecha", fecha);
            SqlDataReader dr = cmd.ExecuteReader();
            if (dr.HasRows)
            {
                while (dr.Read())
                {
                    C_Cliente client = new C_Cliente();
                    client.id_cliente = dr.GetInt32(0);
                    client.documento_identidad = (dr["documento_identidad"].Equals(null) ? null : dr["documento_identidad"].ToString().Trim(new char[] { ' ' }));
                    client.nombre = dr.GetString(2).Trim(new char[] { ' ' });
                    client.apellido = dr.GetString(3).Trim(new char[] { ' ' });
                    client.direccion = (dr["direccion"].Equals(null) ? null : dr["direccion"].ToString().Trim(new char[] { ' ' }));
                    client.correo = (dr["correo"].Equals(null) ? null : dr["correo"].ToString().Trim(new char[] { ' ' }));
                    client.C_TipoDocumento = new Clases.C_TipoDocumento();
                    client.C_TipoDocumento.descripcion = (dr["tipoDoc"].Equals(null) ? null : dr["tipoDoc"].ToString().Trim(new char[] { ' ' }));
                    client.C_Status = new Clases.C_Status();
                    client.C_Status.descripcion = dr.GetString(7).Trim(new char[] { ' ' });
                    client.edo_civil = (dr["edo_civil"].Equals(null) ? null : dr["edo_civil"].ToString().Trim(new char[] { ' ' }));
                    client.edad = (Convert.IsDBNull(dr["edad"]) ? null : (int?)Convert.ToInt32(dr["edad"]));
                    //client.f_nacimiento = (dr["f_nacimiento"].Equals(null) ? null : (DateTime?)Convert.ToDateTime(dr["f_nacimiento"])); 
                    client.C_Locacion = new Clases.C_Locacion();
                    client.C_Locacion.codigo = (dr["locacion"].Equals(null) ? null : dr["locacion"].ToString().Trim(new char[] { ' ' }));
                    client.C_Pais = new Clases.C_Pais();
                    client.C_Pais.nombre = (dr["pais"].Equals(null) ? null : dr["pais"].ToString().Trim(new char[] { ' ' }));
                    client.profesion = (dr["profesion"].Equals(null) ? null : dr["profesion"].ToString().Trim(new char[] { ' ' }));
                    client.t_celular = (dr["t_celular"].Equals(null) ? null : dr["t_celular"].ToString().Trim(new char[] { ' ' }));
                    client.t_habitacion = (dr["t_habitacion"].Equals(null) ? null : dr["t_habitacion"].ToString().Trim(new char[] { ' ' }));
                    client.t_oficina = (dr["t_oficina"].Equals(null) ? null : dr["t_oficina"].ToString().Trim(new char[] { ' ' })); 
                    client.id_status = dr.GetInt32(17);
                    client.id_locacion = (Convert.IsDBNull(dr["id_locacion"]) ? null : (int?)Convert.ToInt32(dr["id_locacion"]));
                    client.id_pais = (Convert.IsDBNull(dr["id_pais"]) ? null : (int?)Convert.ToInt32(dr["id_pais"])); 
                    client.id_td = (Convert.IsDBNull(dr.GetInt32(20)) ? null : (int?)Convert.ToInt32(dr.GetInt32(20)));
                    DateTime? f = (Convert.IsDBNull(dr["f_nacimiento"]) ? null : (DateTime?)Convert.ToDateTime(dr["f_nacimiento"]));
                    DateTime? fc = (Convert.IsDBNull(dr["fecha"]) ? null : (DateTime?)Convert.ToDateTime(dr["fecha"]));
                    client.f_nacimiento = f;
                    client.fecha = fc;
                    client.ola = (dr["hora"].Equals(null) ? null : dr["hora"].ToString().Trim(new char[] { ' ' }));
                    client.asignado = dr.GetInt32(21);
                    client.Id_statusPrincipal = dr.GetInt32(22);
                    client.Id_subStatusCita = (Convert.IsDBNull(dr["statusCita"]) ? null : (int?)Convert.ToInt32(dr["statusCita"]));
                    client.observacion = (dr["observacion"].Equals(null) ? null : dr["observacion"].ToString().Trim(new char[] { ' ' }));
                    client.id_tdA = (Convert.IsDBNull(dr["Expr1"]) ? null : (int?)Convert.ToInt32(dr["Expr1"]));
                    client.documento_identidadA = (dr["Expr2"].Equals(null) ? null : dr["Expr2"].ToString().Trim(new char[] { ' ' }));
                    client.nombreA = (dr["Expr3"].Equals(null) ? null : dr["Expr3"].ToString().Trim(new char[] { ' ' }));
                    client.apellidoA = (dr["Expr4"].Equals(null) ? null : dr["Expr4"].ToString().Trim(new char[] { ' ' }));
                    client.edadA = (Convert.IsDBNull(dr["Expr5"]) ? null : (int?)Convert.ToInt32(dr["Expr5"]));
                    client.profesionA = (dr["ocupacion"].Equals(null) ? null : dr["ocupacion"].ToString().Trim(new char[] { ' ' }));
                    client.telefonoA = (dr["telefono"].Equals(null) ? null : dr["telefono"].ToString().Trim(new char[] { ' ' }));
                    client.correoA = (dr["Expr6"].Equals(null) ? null : dr["Expr6"].ToString().Trim(new char[] { ' ' }));
                    client.statusPrinc = dr.GetString(33).Trim(new char[] { ' ' });
                    client.idPromotor = (Convert.IsDBNull(dr["idPromotor"]) ? null : (int?)Convert.ToInt32(dr["idPromotor"]));
                    client.editando = (Convert.IsDBNull(dr["editando"]) ? null : (int?)Convert.ToInt32(dr["editando"]));
                    clientes.Add(client);

                }
            }
            con.desconectar();
            return clientes;
        }
        public List<C_Cliente> listarAsignacion(int cantidad, DateTime? desde, DateTime? hasta,int? locacion)
        {
            List<C_Cliente> clientes = new List<C_Cliente>();
            if (con == null)
                con = new conexion();
            con.conectar();
            SqlCommand cmd = new SqlCommand("_sp_listarAsignacion", con.cnxn);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@cantidad", cantidad);
            cmd.Parameters.AddWithValue("@desde", desde);
            cmd.Parameters.AddWithValue("@hasta", hasta);
            cmd.Parameters.AddWithValue("@locacion", locacion);
            SqlDataReader dr = cmd.ExecuteReader();
            if (dr.HasRows)
            {
                while (dr.Read())
                {
                    C_Cliente client = new C_Cliente();
                    client.id_cliente = dr.GetInt32(0);
                    client.documento_identidad = (dr["documento_identidad"].Equals(null) ? null : dr["documento_identidad"].ToString().Trim(new char[] { ' ' }));
                    client.nombre = dr.GetString(2).Trim(new char[] { ' ' });
                    client.apellido = dr.GetString(3).Trim(new char[] { ' ' });
                    client.direccion = (dr["direccion"].Equals(null) ? null : dr["direccion"].ToString().Trim(new char[] { ' ' }));
                    client.correo = (dr["correo"].Equals(null) ? null : dr["correo"].ToString().Trim(new char[] { ' ' }));
                    client.C_TipoDocumento = new Clases.C_TipoDocumento();
                    client.C_TipoDocumento.descripcion = (dr["tipoDoc"].Equals(null) ? null : dr["tipoDoc"].ToString().Trim(new char[] { ' ' }));
                    client.C_Status = new Clases.C_Status();
                    client.C_Status.descripcion = dr.GetString(7).Trim(new char[] { ' ' });
                    client.edo_civil = (dr["edo_civil"].Equals(null) ? null : dr["edo_civil"].ToString().Trim(new char[] { ' ' }));
                    client.edad = (Convert.IsDBNull(dr["edad"]) ? null : (int?)Convert.ToInt32(dr["edad"]));
                    //client.f_nacimiento = (dr["f_nacimiento"].Equals(null) ? null : (DateTime?)Convert.ToDateTime(dr["f_nacimiento"])); 
                    client.C_Locacion = new Clases.C_Locacion();
                    client.C_Locacion.codigo = (dr["locacion"].Equals(null) ? null : dr["locacion"].ToString().Trim(new char[] { ' ' }));
                    client.C_Pais = new Clases.C_Pais();
                    client.C_Pais.nombre = (dr["pais"].Equals(null) ? null : dr["pais"].ToString().Trim(new char[] { ' ' }));
                    client.profesion = (dr["profesion"].Equals(null) ? null : dr["profesion"].ToString().Trim(new char[] { ' ' }));
                    client.t_celular = (dr["t_celular"].Equals(null) ? null : dr["t_celular"].ToString().Trim(new char[] { ' ' }));
                    client.t_habitacion = (dr["t_habitacion"].Equals(null) ? null : dr["t_habitacion"].ToString().Trim(new char[] { ' ' }));
                    client.t_oficina = (dr["t_oficina"].Equals(null) ? null : dr["t_oficina"].ToString().Trim(new char[] { ' ' })); 
                    client.id_status = dr.GetInt32(17);
                    client.id_locacion = (Convert.IsDBNull(dr["id_locacion"]) ? null : (int?)Convert.ToInt32(dr["id_locacion"]));
                    client.id_pais = (Convert.IsDBNull(dr["id_pais"]) ? null : (int?)Convert.ToInt32(dr["id_pais"])); 
                    client.id_td = (Convert.IsDBNull(dr.GetInt32(20)) ? null : (int?)Convert.ToInt32(dr.GetInt32(20)));
                    DateTime? f = (Convert.IsDBNull(dr["f_nacimiento"]) ? null : (DateTime?)Convert.ToDateTime(dr["f_nacimiento"]));
                    client.f_nacimiento = f;
                    client.asignado = dr.GetInt32(21);
                    client.Id_statusPrincipal = dr.GetInt32(22);
                    client.Id_subStatusCita = (Convert.IsDBNull(dr["statusCita"]) ? null : (int?)Convert.ToInt32(dr["statusCita"]));
                    client.observacion = (dr["observacion"].Equals(null) ? null : dr["observacion"].ToString().Trim(new char[] { ' ' }));
                    client.id_tdA = (Convert.IsDBNull(dr["Expr1"]) ? null : (int?)Convert.ToInt32(dr["Expr1"]));
                    client.documento_identidadA = (dr["Expr2"].Equals(null) ? null : dr["Expr2"].ToString().Trim(new char[] { ' ' }));
                    client.nombreA = (dr["Expr3"].Equals(null) ? null : dr["Expr3"].ToString().Trim(new char[] { ' ' }));
                    client.apellidoA = (dr["Expr4"].Equals(null) ? null : dr["Expr4"].ToString().Trim(new char[] { ' ' }));
                    client.edadA = (Convert.IsDBNull(dr["Expr5"]) ? null : (int?)Convert.ToInt32(dr["Expr5"]));
                    client.profesionA = (dr["ocupacion"].Equals(null) ? null : dr["ocupacion"].ToString().Trim(new char[] { ' ' }));
                    client.telefonoA = (dr["telefono"].Equals(null) ? null : dr["telefono"].ToString().Trim(new char[] { ' ' }));
                    client.correoA = (dr["Expr6"].Equals(null) ? null : dr["Expr6"].ToString().Trim(new char[] { ' ' }));
                    client.statusPrinc = dr.GetString(33).Trim(new char[] { ' ' });
                    client.idPromotor = (Convert.IsDBNull(dr["idPromotor"]) ? null : (int?)Convert.ToInt32(dr["idPromotor"]));
                    client.editando = (Convert.IsDBNull(dr["editando"]) ? null : (int?)Convert.ToInt32(dr["editando"]));
                    clientes.Add(client);
                   
                }
            }
            con.desconectar();
            return clientes;
        }
        public List<C_Cliente> filtarCLientes(string doc,string telf,string nombres,string apellidos)
        {
            List<C_Cliente> clientes = new List<C_Cliente>();
            if (con == null)
                con = new conexion();
            con.conectar();
            SqlCommand cmd = new SqlCommand("_sp_filtrarClientes", con.cnxn);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@documento", doc);
            cmd.Parameters.AddWithValue("@telefonos", telf);
            cmd.Parameters.AddWithValue("@nombres", nombres);
            cmd.Parameters.AddWithValue("@apellidos", apellidos);
            SqlDataReader dr = cmd.ExecuteReader();
            if (dr.HasRows)
            {
                while (dr.Read())
                {
                    C_Cliente client = new C_Cliente();
                    client.id_cliente = dr.GetInt32(0);
                    client.documento_identidad = (dr["documento_identidad"].Equals(null) ? null : dr["documento_identidad"].ToString().Trim(new char[] { ' ' }));
                    client.nombre = dr.GetString(2).Trim(new char[] { ' ' });
                    client.apellido = dr.GetString(3).Trim(new char[] { ' ' });
                    client.direccion = (dr["direccion"].Equals(null) ? null : dr["direccion"].ToString().Trim(new char[] { ' ' }));
                    client.correo = (dr["correo"].Equals(null) ? null : dr["correo"].ToString().Trim(new char[] { ' ' }));
                    client.C_TipoDocumento = new Clases.C_TipoDocumento();
                    client.C_TipoDocumento.descripcion = (dr["tipoDoc"].Equals(null) ? null : dr["tipoDoc"].ToString().Trim(new char[] { ' ' }));
                    client.C_Status = new Clases.C_Status();
                    client.C_Status.descripcion = dr.GetString(7).Trim(new char[] { ' ' });
                    client.edo_civil = (dr["edo_civil"].Equals(null) ? null : dr["edo_civil"].ToString().Trim(new char[] { ' ' }));
                    client.edad = (Convert.IsDBNull(dr["edad"]) ? null : (int?)Convert.ToInt32(dr["edad"]));
                    //client.f_nacimiento = (dr["f_nacimiento"].Equals(null) ? null : (DateTime?)Convert.ToDateTime(dr["f_nacimiento"])); 
                    client.C_Locacion = new Clases.C_Locacion();
                    client.C_Locacion.codigo = (dr["locacion"].Equals(null) ? null : dr["locacion"].ToString().Trim(new char[] { ' ' }));
                    client.C_Pais = new Clases.C_Pais();
                    client.C_Pais.nombre = (dr["pais"].Equals(null) ? null : dr["pais"].ToString().Trim(new char[] { ' ' }));
                    client.profesion = (dr["profesion"].Equals(null) ? null : dr["profesion"].ToString().Trim(new char[] { ' ' }));
                    client.t_celular = (dr["t_celular"].Equals(null) ? null : dr["t_celular"].ToString().Trim(new char[] { ' ' }));
                    client.t_habitacion = (dr["t_habitacion"].Equals(null) ? null : dr["t_habitacion"].ToString().Trim(new char[] { ' ' }));
                    client.t_oficina = (dr["t_oficina"].Equals(null) ? null : dr["t_oficina"].ToString().Trim(new char[] { ' ' })); 
                    client.id_status = dr.GetInt32(17);
                    client.id_locacion = (Convert.IsDBNull(dr["id_locacion"]) ? null : (int?)Convert.ToInt32(dr["id_locacion"]));
                    client.id_pais = (Convert.IsDBNull(dr["id_pais"]) ? null : (int?)Convert.ToInt32(dr["id_pais"])); 
                    client.id_td = (Convert.IsDBNull(dr.GetInt32(20)) ? null : (int?)Convert.ToInt32(dr.GetInt32(20)));
                    DateTime? f = (Convert.IsDBNull(dr["f_nacimiento"]) ? null : (DateTime?)Convert.ToDateTime(dr["f_nacimiento"]));
                    client.f_nacimiento = f;
                    client.asignado = dr.GetInt32(21);
                    client.Id_statusPrincipal = dr.GetInt32(22);
                    client.Id_subStatusCita = (Convert.IsDBNull(dr["statusCita"]) ? null : (int?)Convert.ToInt32(dr["statusCita"]));
                    client.observacion = (dr["observacion"].Equals(null) ? null : dr["observacion"].ToString().Trim(new char[] { ' ' }));
                    client.id_tdA = (Convert.IsDBNull(dr["Expr1"]) ? null : (int?)Convert.ToInt32(dr["Expr1"]));
                    client.documento_identidadA = (dr["Expr2"].Equals(null) ? null : dr["Expr2"].ToString().Trim(new char[] { ' ' }));
                    client.nombreA = (dr["Expr3"].Equals(null) ? null : dr["Expr3"].ToString().Trim(new char[] { ' ' }));
                    client.apellidoA = (dr["Expr4"].Equals(null) ? null : dr["Expr4"].ToString().Trim(new char[] { ' ' }));
                    client.edadA = (Convert.IsDBNull(dr["Expr5"]) ? null : (int?)Convert.ToInt32(dr["Expr5"]));
                    client.profesionA = (dr["ocupacion"].Equals(null) ? null : dr["ocupacion"].ToString().Trim(new char[] { ' ' }));
                    client.telefonoA = (dr["telefono"].Equals(null) ? null : dr["telefono"].ToString().Trim(new char[] { ' ' }));
                    client.correoA = (dr["Expr6"].Equals(null) ? null : dr["Expr6"].ToString().Trim(new char[] { ' ' }));
                    client.statusPrinc = dr.GetString(33).Trim(new char[] { ' ' });
                    client.idPromotor = (Convert.IsDBNull(dr["idPromotor"]) ? null : (int?)Convert.ToInt32(dr["idPromotor"]));
                    client.editando = (Convert.IsDBNull(dr["editando"]) ? null : (int?)Convert.ToInt32(dr["editando"]));
                    clientes.Add(client);
                }
            }
            con.desconectar();
            return clientes;
        }

        public void guardarAsignacion(int? idTelemarketing, int idciente)
        {           
            if (con == null)
                con = new conexion();
            con.conectar();
            SqlCommand cmd = new SqlCommand("_sp_guardarAsignacion", con.cnxn);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@cliente", idciente);
            cmd.Parameters.AddWithValue("@telemarketing",idTelemarketing);
            cmd.ExecuteNonQuery();
            con.desconectar();           
        }
        public void actualizarAsignacion(int? idTelemarketing, int idciente)
        {
            if (con == null)
                con = new conexion();
            con.conectar();
            SqlCommand cmd = new SqlCommand("_sp_actualizaAsignacion", con.cnxn);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@cliente", idciente);
            cmd.Parameters.AddWithValue("@telemarketing", idTelemarketing);
            cmd.ExecuteNonQuery();
            con.desconectar();
        }
        public void guardarAsignacionCon(int idConfirmador, int idciente)
        {
            if (con == null)
                con = new conexion();
            con.conectar();
            SqlCommand cmd = new SqlCommand("_sp_guardarAsignacionCon", con.cnxn);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@cliente", idciente);
            cmd.Parameters.AddWithValue("@confirmador", idConfirmador);
            cmd.ExecuteNonQuery();
            con.desconectar();
        }

        public List<C_Cliente> filtarAfiliados(string doc, string telf)
        {
            List<C_Cliente> clientes = new List<C_Cliente>();
            if (con == null)
                con = new conexion();
            con.conectar();
            SqlCommand cmd = new SqlCommand("_sp_filtrarClientes", con.cnxn);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@documento", doc);
            cmd.Parameters.AddWithValue("@telefonos", telf);
            SqlDataReader dr = cmd.ExecuteReader();
            if (dr.HasRows)
            {
                while (dr.Read())
                {
                    if (dr.GetInt32(17) == 4)
                    {
                        C_Cliente client = new C_Cliente();
                        client.id_cliente = dr.GetInt32(0);
                        client.documento_identidad = (dr["documento_identidad"].Equals(null) ? null : dr["documento_identidad"].ToString().Trim(new char[] { ' ' }));
                        client.nombre = dr.GetString(2).Trim(new char[] { ' ' });
                        client.apellido = dr.GetString(3).Trim(new char[] { ' ' });
                        client.direccion = (dr["direccion"].Equals(null) ? null : dr["direccion"].ToString().Trim(new char[] { ' ' }));
                        client.correo = (dr["correo"].Equals(null) ? null : dr["correo"].ToString().Trim(new char[] { ' ' }));
                        client.C_TipoDocumento = new Clases.C_TipoDocumento();
                        client.C_TipoDocumento.descripcion = (dr["tipoDoc"].Equals(null) ? null : dr["tipoDoc"].ToString().Trim(new char[] { ' ' }));
                        client.C_Status = new Clases.C_Status();
                        client.C_Status.descripcion = dr.GetString(7).Trim(new char[] { ' ' });
                        client.edo_civil = (dr["edo_civil"].Equals(null) ? null : dr["edo_civil"].ToString().Trim(new char[] { ' ' }));
                        client.edad = (Convert.IsDBNull(dr["edad"]) ? null : (int?)Convert.ToInt32(dr["edad"]));
                        //client.f_nacimiento = (dr["f_nacimiento"].Equals(null) ? null : (DateTime?)Convert.ToDateTime(dr["f_nacimiento"])); 
                        client.C_Locacion = new Clases.C_Locacion();
                        client.C_Locacion.codigo = (dr["locacion"].Equals(null) ? null : dr["locacion"].ToString().Trim(new char[] { ' ' }));
                        client.C_Pais = new Clases.C_Pais();
                        client.C_Pais.nombre = (dr["pais"].Equals(null) ? null : dr["pais"].ToString().Trim(new char[] { ' ' }));
                        client.profesion = (dr["profesion"].Equals(null) ? null : dr["profesion"].ToString().Trim(new char[] { ' ' }));
                        client.t_celular = (dr["t_celular"].Equals(null) ? null : dr["t_celular"].ToString().Trim(new char[] { ' ' }));
                        client.t_habitacion = (dr["t_habitacion"].Equals(null) ? null : dr["t_habitacion"].ToString().Trim(new char[] { ' ' }));
                        client.t_oficina = (dr["t_oficina"].Equals(null) ? null : dr["t_oficina"].ToString().Trim(new char[] { ' ' })); 
                        client.id_status = dr.GetInt32(17);
                        client.id_locacion = (Convert.IsDBNull(dr["id_locacion"]) ? null : (int?)Convert.ToInt32(dr["id_locacion"]));
                        client.id_pais = (Convert.IsDBNull(dr["id_pais"]) ? null : (int?)Convert.ToInt32(dr["id_pais"])); 
                        client.id_td = (Convert.IsDBNull(dr.GetInt32(20)) ? null : (int?)Convert.ToInt32(dr.GetInt32(20)));
                        DateTime? f = (Convert.IsDBNull(dr["f_nacimiento"]) ? null : (DateTime?)Convert.ToDateTime(dr["f_nacimiento"]));
                        client.f_nacimiento = f;
                        client.promotor = dr.GetString(22).Trim(new char[] { ' ' }); ;

                        client.Id_subStatusCita = (Convert.IsDBNull(dr["statusCita"]) ? null : (int?)Convert.ToInt32(dr["statusCita"]));
                        client.observacion = (dr["observacion"].Equals(null) ? null : dr["observacion"].ToString().Trim(new char[] { ' ' }));

                        client.id_tdA = (Convert.IsDBNull(dr["Expr1"]) ? null : (int?)Convert.ToInt32(dr["Expr1"]));
                        client.documento_identidadA = (dr["Expr2"].Equals(null) ? null : dr["Expr2"].ToString().Trim(new char[] { ' ' }));
                        client.nombreA = (dr["Expr3"].Equals(null) ? null : dr["Expr3"].ToString().Trim(new char[] { ' ' }));
                        client.apellidoA = (dr["Expr4"].Equals(null) ? null : dr["Expr4"].ToString().Trim(new char[] { ' ' }));
                        client.edadA = (Convert.IsDBNull(dr["Expr5"]) ? null : (int?)Convert.ToInt32(dr["Expr5"]));
                        client.profesionA = (dr["ocupacion"].Equals(null) ? null : dr["ocupacion"].ToString().Trim(new char[] { ' ' }));
                        client.telefonoA = (dr["telefono"].Equals(null) ? null : dr["telefono"].ToString().Trim(new char[] { ' ' }));
                        client.correoA = (dr["Expr6"].Equals(null) ? null : dr["Expr6"].ToString().Trim(new char[] { ' ' }));
                        client.statusPrinc = dr.GetString(33).Trim(new char[] { ' ' });
                        client.idPromotor = (Convert.IsDBNull(dr["idPromotor"]) ? null : (int?)Convert.ToInt32(dr["idPromotor"]));
                        client.editando = (Convert.IsDBNull(dr["editando"]) ? null : (int?)Convert.ToInt32(dr["editando"]));
                        clientes.Add(client);
                    }
                }
            }
            con.desconectar();
            return clientes;
        }

        public int NuevoCliente(int iduser)
        {
            try
            {
                if (con == null)
                    con = new conexion();
                con.conectar();
                SqlCommand cmd = new SqlCommand("_sp_nuevoCliente", con.cnxn);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@idTd", id_td);
                cmd.Parameters.AddWithValue("@documento", documento_identidad);
                cmd.Parameters.AddWithValue("@nombre", nombre);
                cmd.Parameters.AddWithValue("@apellido", apellido);
                cmd.Parameters.AddWithValue("@idPais", id_pais);
                cmd.Parameters.AddWithValue("@direccion", direccion);
                cmd.Parameters.AddWithValue("@tHabitacion", t_habitacion);
                cmd.Parameters.AddWithValue("@tCelular", t_celular);
                cmd.Parameters.AddWithValue("@tOficina", t_oficina);
                cmd.Parameters.AddWithValue("@idStatus", id_status);
                cmd.Parameters.AddWithValue("@idLocacion", id_locacion);
                cmd.Parameters.AddWithValue("@correo", correo);
                cmd.Parameters.AddWithValue("@profesion", profesion);
                cmd.Parameters.AddWithValue("@edad", edad);
                cmd.Parameters.AddWithValue("@edoCivil", edo_civil);
                cmd.Parameters.AddWithValue("@fNacimiento", f_nacimiento);
                cmd.Parameters.AddWithValue("@statusPrin", Id_statusPrincipal);
                cmd.Parameters.AddWithValue("@statusCita", Id_subStatusCita);             
                cmd.Parameters.AddWithValue("@asignado", asignado);
                cmd.Parameters.AddWithValue("@observ", observacion);
                cmd.Parameters.AddWithValue("@promotor",idPromotor);
                cmd.Parameters.AddWithValue("@usuario", iduser);  
                cmd.ExecuteNonQuery();
                con.desconectar();
                return 1;
            }
            catch
            {
                con.desconectar();
                return 0;
            }
        }

        public int editarCliente()
        {
            try
            {
                if (con == null)
                    con = new conexion();
                con.conectar();
                SqlCommand cmd = new SqlCommand("_sp_editarCliente", con.cnxn);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@id", id_cliente);
                cmd.Parameters.AddWithValue("@idTd", id_td);
                cmd.Parameters.AddWithValue("@documento", documento_identidad);
                cmd.Parameters.AddWithValue("@nombre", nombre);
                cmd.Parameters.AddWithValue("@apellido", apellido);
                cmd.Parameters.AddWithValue("@idPais", id_pais);
                cmd.Parameters.AddWithValue("@direccion", direccion);
                cmd.Parameters.AddWithValue("@tHabitacion", t_habitacion);
                cmd.Parameters.AddWithValue("@tCelular", t_celular);
                cmd.Parameters.AddWithValue("@tOficina", t_oficina);
                cmd.Parameters.AddWithValue("@idStatus", id_status);
                cmd.Parameters.AddWithValue("@idLocacion", id_locacion);
                cmd.Parameters.AddWithValue("@correo", correo);
                cmd.Parameters.AddWithValue("@profesion", profesion);
                cmd.Parameters.AddWithValue("@edad", edad);
                cmd.Parameters.AddWithValue("@edoCivil", edo_civil);
                cmd.Parameters.AddWithValue("@fNacimiento", f_nacimiento);
                cmd.Parameters.AddWithValue("@idStatusP", Id_statusPrincipal);
                cmd.Parameters.AddWithValue("@idSubStatusCita", Id_subStatusCita);                          
                cmd.Parameters.AddWithValue("@observacion", observacion);
                cmd.Parameters.AddWithValue("@promotor", idPromotor);
                cmd.ExecuteNonQuery();
                con.desconectar();
                return 1;
            }
            catch
            {
                con.desconectar();
                return 0;
            }
        }

        public int NuevoAcomp()
        {
            try
            {
                if (con == null)
                    con = new conexion();
                con.conectar();
                SqlCommand cmd = new SqlCommand("_sp_nuevoAcomp", con.cnxn);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@idTd", id_tdA);
                cmd.Parameters.AddWithValue("@documento", documento_identidadA);
                cmd.Parameters.AddWithValue("@nombre", nombreA);
                cmd.Parameters.AddWithValue("@apellido", apellidoA);                
                cmd.Parameters.AddWithValue("@correo", correo);
                cmd.Parameters.AddWithValue("@profesion", profesionA);
                cmd.Parameters.AddWithValue("@edad", edadA);
                cmd.Parameters.AddWithValue("@telefono", telefonoA);
                cmd.Parameters.AddWithValue("@cliente", id_cliente);
                cmd.ExecuteNonQuery();
                con.desconectar();
                return 1;
            }
            catch
            {
                con.desconectar();
                return 0;
            }
        }
        public int verificaAcomp()
        {
            try
            {
                if (con == null)
                    con = new conexion();
                con.conectar();
                SqlCommand cmd = new SqlCommand("_sp_verificaAcomp", con.cnxn);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@id", id_cliente);
                SqlDataReader dr = cmd.ExecuteReader();
                if (dr.HasRows)
                {
                    con.desconectar();
                    return 1;
                }
                else
                {
                    con.desconectar();
                    return 0;
                }
            }
            catch
            {
                con.desconectar();
                return 2;
            }
        }
        
        public int editarAcomp()
        {
            try
            {
                if (con == null)
                    con = new conexion();
                con.conectar();
                SqlCommand cmd = new SqlCommand("_sp_editarAcomp", con.cnxn);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@idTd", id_tdA);
                cmd.Parameters.AddWithValue("@documento", documento_identidadA);
                cmd.Parameters.AddWithValue("@nombre", nombreA);
                cmd.Parameters.AddWithValue("@apellido", apellidoA);
                cmd.Parameters.AddWithValue("@correo", correo);
                cmd.Parameters.AddWithValue("@profesion", profesionA);
                cmd.Parameters.AddWithValue("@edad", edadA);
                cmd.Parameters.AddWithValue("@telefono", telefonoA);
                cmd.Parameters.AddWithValue("@cliente", id_cliente);
                cmd.ExecuteNonQuery();
                con.desconectar();
                return 1;
            }
            catch
            {
                con.desconectar();
                return 0;
            }
        }
        public int detalleCita()
        {
            try
            {
                if (con == null)
                    con = new conexion();
                con.conectar();
                SqlCommand cmd = new SqlCommand("_sp_detalleCita", con.cnxn);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@idTd", id_tdA);
                cmd.Parameters.AddWithValue("@documento", documento_identidadA);
                cmd.Parameters.AddWithValue("@nombre", nombreA);
                cmd.Parameters.AddWithValue("@apellido", apellidoA);
                cmd.Parameters.AddWithValue("@correo", correo);
                cmd.Parameters.AddWithValue("@profesion", profesionA);
                cmd.Parameters.AddWithValue("@edad", edadA);
                cmd.Parameters.AddWithValue("@telefono", telefonoA);
                cmd.Parameters.AddWithValue("@cliente", id_cliente);
                cmd.ExecuteNonQuery();
                con.desconectar();
                return 1;
            }
            catch
            {
                con.desconectar();
                return 0;
            }
        }

        public int registarCambioStatus(int iduser)
        {
            try
            {
                if (con == null)
                    con = new conexion();
                con.conectar();
                SqlCommand cmd = new SqlCommand("_sp_registrarCambioStts", con.cnxn);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@fecha", DateTime.Now);
                cmd.Parameters.AddWithValue("@cliente", id_cliente);
                cmd.Parameters.AddWithValue("@statusPrin", Id_statusPrincipal);
                cmd.Parameters.AddWithValue("@Status", id_status);
                cmd.Parameters.AddWithValue("@SubSttsCita", Id_subStatusCita);
                cmd.Parameters.AddWithValue("@usuario", iduser);               
                cmd.ExecuteNonQuery();
                con.desconectar();
                return 1;
            }
            catch
            {
                con.desconectar();
                return 0;
            }
        }
        public List<C_Cliente> ReporteCLientes(DateTime? desde, DateTime? hasta,int? locacion)
        {
            List<C_Cliente> clientes = new List<C_Cliente>();
            if (con == null)
                con = new conexion();
            con.conectar();
            SqlCommand cmd = new SqlCommand("_sp_reporteClientes", con.cnxn);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@idStatus", id_status);
            cmd.Parameters.AddWithValue("@fechaDesde", desde);
            cmd.Parameters.AddWithValue("@fechaHasta", hasta);
            cmd.Parameters.AddWithValue("@statusPrincipal", Id_statusPrincipal);
            cmd.Parameters.AddWithValue("@locacion",locacion);
            SqlDataReader dr = cmd.ExecuteReader();
            if (dr.HasRows)
            {
                while (dr.Read())
                {
                    C_Cliente client = new C_Cliente();
                    client.id_cliente = dr.GetInt32(0);
                    client.documento_identidad = (dr["documento_identidad"].Equals(null) ? null : dr["documento_identidad"].ToString().Trim(new char[] { ' ' }));
                    client.nombre = dr.GetString(2).Trim(new char[] { ' ' });
                    client.apellido = dr.GetString(3).Trim(new char[] { ' ' });
                    client.direccion = (dr["direccion"].Equals(null) ? null : dr["direccion"].ToString().Trim(new char[] { ' ' }));
                    client.correo = (dr["correo"].Equals(null) ? null : dr["correo"].ToString().Trim(new char[] { ' ' }));
                    client.C_TipoDocumento = new Clases.C_TipoDocumento();
                    client.C_TipoDocumento.descripcion = (dr["tipoDoc"].Equals(null) ? null : dr["tipoDoc"].ToString().Trim(new char[] { ' ' }));
                    client.C_Status = new Clases.C_Status();
                    client.C_Status.descripcion = dr.GetString(7).Trim(new char[] { ' ' });
                    client.edo_civil = (dr["edo_civil"].Equals(null) ? null : dr["edo_civil"].ToString().Trim(new char[] { ' ' }));
                    client.edad = (Convert.IsDBNull(dr["edad"]) ? null : (int?)Convert.ToInt32(dr["edad"]));
                    //client.f_nacimiento = (dr["f_nacimiento"].Equals(null) ? null : (DateTime?)Convert.ToDateTime(dr["f_nacimiento"])); 
                    client.C_Locacion = new Clases.C_Locacion();
                    client.C_Locacion.codigo = (dr["locacion"].Equals(null) ? null : dr["locacion"].ToString().Trim(new char[] { ' ' }));
                    client.C_Pais = new Clases.C_Pais();
                    client.C_Pais.nombre = (dr["pais"].Equals(null) ? null : dr["pais"].ToString().Trim(new char[] { ' ' }));
                    client.profesion = (dr["profesion"].Equals(null) ? null : dr["profesion"].ToString().Trim(new char[] { ' ' }));
                    client.t_celular = (dr["t_celular"].Equals(null) ? null : dr["t_celular"].ToString().Trim(new char[] { ' ' }));
                    client.t_habitacion = (dr["t_habitacion"].Equals(null) ? null : dr["t_habitacion"].ToString().Trim(new char[] { ' ' }));
                    client.t_oficina = (dr["t_oficina"].Equals(null) ? null : dr["t_oficina"].ToString().Trim(new char[] { ' ' })); 
                    client.id_status = dr.GetInt32(17);
                    client.id_locacion = (Convert.IsDBNull(dr["id_locacion"]) ? null : (int?)Convert.ToInt32(dr["id_locacion"]));
                    client.id_pais = (Convert.IsDBNull(dr["id_pais"]) ? null : (int?)Convert.ToInt32(dr["id_pais"])); 
                    client.id_td = (Convert.IsDBNull(dr.GetInt32(20)) ? null : (int?)Convert.ToInt32(dr.GetInt32(20)));
                    DateTime? f = (Convert.IsDBNull(dr["f_nacimiento"]) ? null : (DateTime?)Convert.ToDateTime(dr["f_nacimiento"]));
                    client.f_nacimiento = f;
                    client.asignado = dr.GetInt32(21);
                    client.Id_statusPrincipal = dr.GetInt32(22);
                    client.Id_subStatusCita = (Convert.IsDBNull(dr["statusCita"]) ? null : (int?)Convert.ToInt32(dr["statusCita"]));
                    client.observacion = (dr["observacion"].Equals(null) ? null : dr["observacion"].ToString().Trim(new char[] { ' ' }));
                    client.id_tdA = (Convert.IsDBNull(dr["Expr1"]) ? null : (int?)Convert.ToInt32(dr["Expr1"]));
                    client.documento_identidadA = (dr["Expr2"].Equals(null) ? null : dr["Expr2"].ToString().Trim(new char[] { ' ' }));
                    client.nombreA = (dr["Expr3"].Equals(null) ? null : dr["Expr3"].ToString().Trim(new char[] { ' ' }));
                    client.apellidoA = (dr["Expr4"].Equals(null) ? null : dr["Expr4"].ToString().Trim(new char[] { ' ' }));
                    client.edadA = (Convert.IsDBNull(dr["Expr5"]) ? null : (int?)Convert.ToInt32(dr["Expr5"]));
                    client.profesionA = (dr["ocupacion"].Equals(null) ? null : dr["ocupacion"].ToString().Trim(new char[] { ' ' }));
                    client.telefonoA = (dr["telefono"].Equals(null) ? null : dr["telefono"].ToString().Trim(new char[] { ' ' }));
                    client.correoA = (dr["Expr6"].Equals(null) ? null : dr["Expr6"].ToString().Trim(new char[] { ' ' }));
                    client.statusPrinc = dr.GetString(33).Trim(new char[] { ' ' });
                    client.idPromotor = (Convert.IsDBNull(dr["idPromotor"]) ? null : (int?)Convert.ToInt32(dr["idPromotor"]));
                    client.editando = (Convert.IsDBNull(dr["editando"]) ? null : (int?)Convert.ToInt32(dr["editando"]));
                    clientes.Add(client);
                }
            }
            con.desconectar();
            return clientes;
        }
        public List<C_Cliente> listarPendientes(int tele)
        {
            List<C_Cliente> clientes = new List<C_Cliente>();
            if (con == null)
                con = new conexion();
            con.conectar();
            SqlCommand cmd = new SqlCommand("_sp_listarPendientes", con.cnxn);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@Tele", tele);
            SqlDataReader dr = cmd.ExecuteReader();
            if (dr.HasRows)
            {
                while (dr.Read())
                {
                    if (dr.GetInt32(17) != 4)
                    {
                        C_Cliente client = new C_Cliente();
                        client.id_cliente = dr.GetInt32(0);
                        client.documento_identidad = (dr["documento_identidad"].Equals(null) ? null : dr["documento_identidad"].ToString().Trim(new char[] { ' ' }));
                        client.nombre = dr.GetString(2).Trim(new char[] { ' ' });
                        client.apellido = dr.GetString(3).Trim(new char[] { ' ' });
                        client.direccion = (dr["direccion"].Equals(null) ? null : dr["direccion"].ToString().Trim(new char[] { ' ' }));
                        client.correo = (dr["correo"].Equals(null) ? null : dr["correo"].ToString().Trim(new char[] { ' ' }));
                        client.C_TipoDocumento = new Clases.C_TipoDocumento();
                        client.C_TipoDocumento.descripcion = (dr["tipoDoc"].Equals(null) ? null : dr["tipoDoc"].ToString().Trim(new char[] { ' ' }));
                        client.C_Status = new Clases.C_Status();
                        client.C_Status.descripcion = dr.GetString(7).Trim(new char[] { ' ' });
                        client.edo_civil = (dr["edo_civil"].Equals(null) ? null : dr["edo_civil"].ToString().Trim(new char[] { ' ' }));
                        client.edad = (Convert.IsDBNull(dr["edad"]) ? null : (int?)Convert.ToInt32(dr["edad"]));
                        //client.f_nacimiento = (dr["f_nacimiento"].Equals(null) ? null : (DateTime?)Convert.ToDateTime(dr["f_nacimiento"])); 
                        client.C_Locacion = new Clases.C_Locacion();
                        client.C_Locacion.codigo = (dr["locacion"].Equals(null) ? null : dr["locacion"].ToString().Trim(new char[] { ' ' }));
                        client.C_Pais = new Clases.C_Pais();
                        client.C_Pais.nombre = (dr["pais"].Equals(null) ? null : dr["pais"].ToString().Trim(new char[] { ' ' }));
                        client.profesion = (dr["profesion"].Equals(null) ? null : dr["profesion"].ToString().Trim(new char[] { ' ' }));
                        client.t_celular = (dr["t_celular"].Equals(null) ? null : dr["t_celular"].ToString().Trim(new char[] { ' ' }));
                        client.t_habitacion = (dr["t_habitacion"].Equals(null) ? null : dr["t_habitacion"].ToString().Trim(new char[] { ' ' }));
                        client.t_oficina = (dr["t_oficina"].Equals(null) ? null : dr["t_oficina"].ToString().Trim(new char[] { ' ' })); 
                        client.id_status = dr.GetInt32(17);
                        client.id_locacion = (Convert.IsDBNull(dr["id_locacion"]) ? null : (int?)Convert.ToInt32(dr["id_locacion"]));
                        client.id_pais = (Convert.IsDBNull(dr["id_pais"]) ? null : (int?)Convert.ToInt32(dr["id_pais"])); 
                        client.id_td = (Convert.IsDBNull(dr.GetInt32(20)) ? null : (int?)Convert.ToInt32(dr.GetInt32(20)));
                        DateTime? f = (Convert.IsDBNull(dr["f_nacimiento"]) ? null : (DateTime?)Convert.ToDateTime(dr["f_nacimiento"]));
                        client.f_nacimiento = f;                        
                        client.asignado = dr.GetInt32(21);
                        client.Id_statusPrincipal = dr.GetInt32(22);
                        client.Id_subStatusCita = (Convert.IsDBNull(dr["statusCita"]) ? null : (int?)Convert.ToInt32(dr["statusCita"]));
                        client.observacion = (dr["observacion"].Equals(null) ? null : dr["observacion"].ToString().Trim(new char[] { ' ' }));
                        client.id_tdA = (Convert.IsDBNull(dr["Expr1"]) ? null : (int?)Convert.ToInt32(dr["Expr1"]));
                        client.documento_identidadA = (dr["Expr2"].Equals(null) ? null : dr["Expr2"].ToString().Trim(new char[] { ' ' }));
                        client.nombreA = (dr["Expr3"].Equals(null) ? null : dr["Expr3"].ToString().Trim(new char[] { ' ' }));
                        client.apellidoA = (dr["Expr4"].Equals(null) ? null : dr["Expr4"].ToString().Trim(new char[] { ' ' }));
                        client.edadA = (Convert.IsDBNull(dr["Expr5"]) ? null : (int?)Convert.ToInt32(dr["Expr5"]));
                        client.profesionA = (dr["ocupacion"].Equals(null) ? null : dr["ocupacion"].ToString().Trim(new char[] { ' ' }));
                        client.telefonoA = (dr["telefono"].Equals(null) ? null : dr["telefono"].ToString().Trim(new char[] { ' ' }));
                        client.correoA = (dr["Expr6"].Equals(null) ? null : dr["Expr6"].ToString().Trim(new char[] { ' ' }));
                        client.idPromotor = (Convert.IsDBNull(dr["idPromotor"]) ? null : (int?)Convert.ToInt32(dr["idPromotor"]));
                        client.editando = (Convert.IsDBNull(dr["editando"]) ? null : (int?)Convert.ToInt32(dr["editando"]));
                        clientes.Add(client);
                    }
                }
            }
            con.desconectar();
            return clientes;
        }

        public List<C_Cliente> ReporteAsignacion(DateTime? fi,DateTime? ff,int? tele)
        {
            List<C_Cliente> clientes = new List<C_Cliente>();
            if (con == null)
                con = new conexion();
            con.conectar();
            SqlCommand cmd = new SqlCommand("_sp_ReporteAsignacion", con.cnxn);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@Tele", tele);
            cmd.Parameters.AddWithValue("@fi", fi);
            cmd.Parameters.AddWithValue("@ff", ff);
            SqlDataReader dr = cmd.ExecuteReader();
            if (dr.HasRows)
            {
                while (dr.Read())
                {
                    if (dr.GetInt32(17) != 4)
                    {
                        C_Cliente client = new C_Cliente();
                        client.id_cliente = dr.GetInt32(0);
                        client.documento_identidad = (dr["documento_identidad"].Equals(null) ? null : dr["documento_identidad"].ToString().Trim(new char[] { ' ' }));
                        client.nombre = dr.GetString(2).Trim(new char[] { ' ' });
                        client.apellido = dr.GetString(3).Trim(new char[] { ' ' });
                        client.direccion = (dr["direccion"].Equals(null) ? null : dr["direccion"].ToString().Trim(new char[] { ' ' }));
                        client.correo = (dr["correo"].Equals(null) ? null : dr["correo"].ToString().Trim(new char[] { ' ' }));
                        client.C_TipoDocumento = new Clases.C_TipoDocumento();
                        client.C_TipoDocumento.descripcion = (dr["tipoDoc"].Equals(null) ? null : dr["tipoDoc"].ToString().Trim(new char[] { ' ' }));
                        client.C_Status = new Clases.C_Status();
                        client.C_Status.descripcion = dr.GetString(7).Trim(new char[] { ' ' });
                        client.edo_civil = (dr["edo_civil"].Equals(null) ? null : dr["edo_civil"].ToString().Trim(new char[] { ' ' }));
                        client.edad = (Convert.IsDBNull(dr["edad"]) ? null : (int?)Convert.ToInt32(dr["edad"]));
                        //client.f_nacimiento = (dr["f_nacimiento"].Equals(null) ? null : (DateTime?)Convert.ToDateTime(dr["f_nacimiento"])); 
                        client.C_Locacion = new Clases.C_Locacion();
                        client.C_Locacion.codigo = (dr["locacion"].Equals(null) ? null : dr["locacion"].ToString().Trim(new char[] { ' ' }));
                        client.C_Pais = new Clases.C_Pais();
                        client.C_Pais.nombre = (dr["pais"].Equals(null) ? null : dr["pais"].ToString().Trim(new char[] { ' ' }));
                        client.profesion = (dr["profesion"].Equals(null) ? null : dr["profesion"].ToString().Trim(new char[] { ' ' }));
                        client.t_celular = (dr["t_celular"].Equals(null) ? null : dr["t_celular"].ToString().Trim(new char[] { ' ' }));
                        client.t_habitacion = (dr["t_habitacion"].Equals(null) ? null : dr["t_habitacion"].ToString().Trim(new char[] { ' ' }));
                        client.t_oficina = (dr["t_oficina"].Equals(null) ? null : dr["t_oficina"].ToString().Trim(new char[] { ' ' })); 
                        client.id_status = dr.GetInt32(17);
                        client.id_locacion = (Convert.IsDBNull(dr["id_locacion"]) ? null : (int?)Convert.ToInt32(dr["id_locacion"]));
                        client.id_pais = (Convert.IsDBNull(dr["id_pais"]) ? null : (int?)Convert.ToInt32(dr["id_pais"])); 
                        client.id_td = (Convert.IsDBNull(dr.GetInt32(20)) ? null : (int?)Convert.ToInt32(dr.GetInt32(20)));
                        DateTime? f = (Convert.IsDBNull(dr["f_nacimiento"]) ? null : (DateTime?)Convert.ToDateTime(dr["f_nacimiento"]));
                        client.f_nacimiento = f;                      
                        client.asignado = dr.GetInt32(21);
                        client.Id_statusPrincipal = dr.GetInt32(22);
                        client.Id_subStatusCita = (Convert.IsDBNull(dr["statusCita"]) ? null : (int?)Convert.ToInt32(dr["statusCita"]));
                        client.observacion = (dr["observacion"].Equals(null) ? null : dr["observacion"].ToString().Trim(new char[] { ' ' }));
                        client.id_tdA = (Convert.IsDBNull(dr["Expr1"]) ? null : (int?)Convert.ToInt32(dr["Expr1"]));
                        client.documento_identidadA = (dr["Expr2"].Equals(null) ? null : dr["Expr2"].ToString().Trim(new char[] { ' ' }));
                        client.nombreA = (dr["Expr3"].Equals(null) ? null : dr["Expr3"].ToString().Trim(new char[] { ' ' }));
                        client.apellidoA = (dr["Expr4"].Equals(null) ? null : dr["Expr4"].ToString().Trim(new char[] { ' ' }));
                        client.edadA = (Convert.IsDBNull(dr["Expr5"]) ? null : (int?)Convert.ToInt32(dr["Expr5"]));
                        client.profesionA = (dr["ocupacion"].Equals(null) ? null : dr["ocupacion"].ToString().Trim(new char[] { ' ' }));
                        client.telefonoA = (dr["telefono"].Equals(null) ? null : dr["telefono"].ToString().Trim(new char[] { ' ' }));
                        client.correoA = (dr["Expr6"].Equals(null) ? null : dr["Expr6"].ToString().Trim(new char[] { ' ' }));
                        client.editando = (Convert.IsDBNull(dr["editando"]) ? null : (int?)Convert.ToInt32(dr["editando"]));
                        clientes.Add(client);
                    }
                }
            }
            con.desconectar();
            return clientes;
        }

        public List<KeyValuePair<string, DateTime>> historial()
        {
            List<KeyValuePair<string, DateTime>> valueList = new List<KeyValuePair<string, DateTime>>();
            if (con == null)
                con = new conexion();
            con.conectar();
            SqlCommand cmd = new SqlCommand("_sp_Historial", con.cnxn);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@cliente", id_cliente);
              SqlDataReader dr = cmd.ExecuteReader();
              if (dr.HasRows)
              {
                  while (dr.Read())
                  {
                      valueList.Add(new KeyValuePair<string, DateTime>(dr.GetString(3).Trim(new char[] { ' ' }) + " Modificado Por: " + dr.GetString(6).Trim(new char[] { ' ' }), dr.GetDateTime(1)));
                  }
              }
              con.desconectar();
              return valueList;
            
        }
        public List<KeyValuePair<string, DateTime>> historialContactado()
        {
            List<KeyValuePair<string, DateTime>> valueList = new List<KeyValuePair<string, DateTime>>();
            if (con == null)
                con = new conexion();
            con.conectar();
            SqlCommand cmd = new SqlCommand("_sp_HistorialCon", con.cnxn);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@cliente", id_cliente);
            SqlDataReader dr = cmd.ExecuteReader();
            if (dr.HasRows)
            {
                while (dr.Read())
                {
                    valueList.Add(new KeyValuePair<string, DateTime>(dr.GetString(3).Trim(new char[] { ' ' }) + " Modificado Por: " + dr.GetString(6).Trim(new char[] { ' ' }), dr.GetDateTime(1)));
                }
            }
            con.desconectar();
            return valueList;

        }
        public int existeNumero(string numero)
        {
            if (con == null)
                con = new conexion();
            con.conectar();
            SqlCommand cmd = new SqlCommand("_sp_existeNumero", con.cnxn);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@numero", numero);
            SqlDataReader dr = cmd.ExecuteReader();
            if (dr.HasRows)
            {
                con.desconectar();
                return 1;
            }
            else
            {
                con.desconectar();
                return 0;
            }
        }

        public void ActEdit(int idcliente,int edit)
        {
            try
            {
                if (con == null)
                    con = new conexion();
                con.conectar();
                SqlCommand cmd = new SqlCommand("_sp_actualizaEditando", con.cnxn);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@edit", edit);
                cmd.Parameters.AddWithValue("@cliente", idcliente);
              
                cmd.ExecuteNonQuery();
                con.desconectar();
              
            }
            catch
            {
                con.desconectar();
                
            }
        }

        public int verificaEdit(int cliente)
        {
            if (con == null)
                con = new conexion();
            con.conectar();
            SqlCommand cmd = new SqlCommand("_sp_verificaEdit", con.cnxn);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@cliente", cliente);
            SqlDataReader dr = cmd.ExecuteReader();
            int resp = -1;
            if (dr.HasRows)
            {
                if(dr.Read())
                    resp = dr.GetInt32(0);
            }
            con.desconectar();
            return resp;
        }


        #region INotifyPropertyChanged Members

        public event PropertyChangedEventHandler PropertyChanged;
        private void OnChanged(string prop)
        {
            if (PropertyChanged != null)
                PropertyChanged(this, new PropertyChangedEventArgs(prop));
        }

        #endregion
    }
     
}
