/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package secunefa;
import javax.swing.table.*;
import Clases.*;
import java.awt.*; 
import java.io.*;
import javax.swing.*;
/**
 *
 * @author salazar
 */
public class AsignarNota extends javax.swing.JFrame {
    String carrera,asignatura,codigo,seccion,cedulaalumno;
    /**
     * Creates new form AsignarNota
     */
    public AsignarNota(String carr,String asign,String cod,String sec,String ced) {
        initComponents();
        carrera=carr;
        asignatura=asign;
        codigo=cod;
        seccion=sec;
        cedulaalumno=ced;
        String texto,texto2,texto3,texto4;
        texto="*Carrera: "+carrera;
        texto2=" Materia: "+asign;
        texto3=" Código: "+cod;
        texto4=" Sección: "+sec;
        EtqCarrera.setText(texto);
        EtqMateria.setText(texto2);
        EtqCodigo.setText(texto3);
        EtqSeccion.setText(texto4);
        try{
            ObjectInputStream entrada=new ObjectInputStream(new FileInputStream("alumno.obj"));
            alumno aux=(alumno)entrada.readObject();
            entrada.close();
            while (aux!=null)
            {
                if(ced.equals(aux.cedula))
                {
                    texto="*Cédula: "+aux.cedula;
                    texto2=" Nombre: "+aux.nombre;
                    texto3=" Apellido: "+aux.apellido;
                    texto4=" Direccion: "+aux.direccion;
                    EtqCedula.setText(texto);
                    EtqNombre.setText(texto2);
                    EtqApellido.setText(texto3);
                    EtqDireccion.setText(texto4);
                }
                aux=aux.sig;
            }
        }
        catch (IOException ex) {
        System.out.println(ex);
        }catch (ClassNotFoundException ex) {
               System.out.println(ex);
        }
        setSize(624,576);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Mensaje = new javax.swing.JOptionPane();
        PanelVentana = new javax.swing.JPanel();
        PanelBanner = new javax.swing.JPanel();
        PanelCuerpo = new javax.swing.JPanel();
        EtqDatosAlumno = new javax.swing.JLabel();
        EtqCedula = new javax.swing.JLabel();
        EtqNombre = new javax.swing.JLabel();
        EtqApellido = new javax.swing.JLabel();
        EtqDireccion = new javax.swing.JLabel();
        ComboNota = new javax.swing.JComboBox();
        EtqNota = new javax.swing.JLabel();
        BotonRegresar = new javax.swing.JButton();
        BotonGuardar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        EtqCarrera = new javax.swing.JLabel();
        EtqMateria = new javax.swing.JLabel();
        EtqCodigo = new javax.swing.JLabel();
        EtqSeccion = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Asignar Nota");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        org.jdesktop.layout.GroupLayout PanelBannerLayout = new org.jdesktop.layout.GroupLayout(PanelBanner);
        PanelBanner.setLayout(PanelBannerLayout);
        PanelBannerLayout.setHorizontalGroup(
            PanelBannerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 0, Short.MAX_VALUE)
        );
        PanelBannerLayout.setVerticalGroup(
            PanelBannerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 130, Short.MAX_VALUE)
        );

        PanelCuerpo.setBackground(new java.awt.Color(255, 255, 255));

        EtqDatosAlumno.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        EtqDatosAlumno.setText("DATOS DEL ALUMNO");

        EtqCedula.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        EtqCedula.setText("DATOS DEL ALUMNO");

        EtqNombre.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        EtqNombre.setText("DATOS DEL ALUMNO");

        EtqApellido.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        EtqApellido.setText("DATOS DEL ALUMNO");

        EtqDireccion.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        EtqDireccion.setText("DATOS DEL ALUMNO");

        ComboNota.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione...", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));

        EtqNota.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        EtqNota.setText("*Nota");

        BotonRegresar.setText("Regresar");
        BotonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegresarActionPerformed(evt);
            }
        });

        BotonGuardar.setText("Guardar");
        BotonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        jLabel2.setText("DATOS DE LA CARRERA");

        EtqCarrera.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        EtqCarrera.setText("DATOS DEL ALUMNO");

        EtqMateria.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        EtqMateria.setText("DATOS DEL ALUMNO");

        EtqCodigo.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        EtqCodigo.setText("DATOS DEL ALUMNO");

        EtqSeccion.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        EtqSeccion.setText("DATOS DEL ALUMNO");

        jLabel3.setFont(new java.awt.Font("Lucida Console", 1, 16)); // NOI18N
        jLabel3.setText("AGREGAR NOTA");

        org.jdesktop.layout.GroupLayout PanelCuerpoLayout = new org.jdesktop.layout.GroupLayout(PanelCuerpo);
        PanelCuerpo.setLayout(PanelCuerpoLayout);
        PanelCuerpoLayout.setHorizontalGroup(
            PanelCuerpoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, PanelCuerpoLayout.createSequentialGroup()
                .add(0, 0, Short.MAX_VALUE)
                .add(BotonGuardar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(BotonRegresar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(180, 180, 180))
            .add(PanelCuerpoLayout.createSequentialGroup()
                .addContainerGap()
                .add(PanelCuerpoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, PanelCuerpoLayout.createSequentialGroup()
                        .add(0, 227, Short.MAX_VALUE)
                        .add(PanelCuerpoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, PanelCuerpoLayout.createSequentialGroup()
                                .add(EtqNota, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(ComboNota, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(226, 226, 226))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, PanelCuerpoLayout.createSequentialGroup()
                                .add(jLabel3)
                                .add(233, 233, 233))))
                    .add(PanelCuerpoLayout.createSequentialGroup()
                        .add(10, 10, 10)
                        .add(PanelCuerpoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(EtqApellido)
                            .add(EtqNombre)
                            .add(EtqCedula)
                            .add(EtqDatosAlumno)
                            .add(EtqDireccion))
                        .addContainerGap())
                    .add(PanelCuerpoLayout.createSequentialGroup()
                        .add(PanelCuerpoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(PanelCuerpoLayout.createSequentialGroup()
                                .add(10, 10, 10)
                                .add(PanelCuerpoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(jLabel2)
                                    .add(PanelCuerpoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(EtqMateria)
                                        .add(EtqCarrera)
                                        .add(EtqCodigo)
                                        .add(EtqSeccion)))
                                .add(0, 0, Short.MAX_VALUE))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jSeparator3)
                            .add(jSeparator2)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jSeparator1))
                        .addContainerGap())))
        );
        PanelCuerpoLayout.setVerticalGroup(
            PanelCuerpoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, PanelCuerpoLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jLabel3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(EtqCarrera)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(EtqMateria)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(EtqCodigo)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(EtqSeccion)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(5, 5, 5)
                .add(EtqDatosAlumno)
                .add(18, 18, 18)
                .add(EtqCedula)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(EtqNombre)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(EtqApellido)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(EtqDireccion)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(PanelCuerpoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(ComboNota, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(EtqNota))
                .add(18, 18, 18)
                .add(PanelCuerpoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(BotonRegresar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(BotonGuardar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(31, 31, 31))
        );

        org.jdesktop.layout.GroupLayout PanelVentanaLayout = new org.jdesktop.layout.GroupLayout(PanelVentana);
        PanelVentana.setLayout(PanelVentanaLayout);
        PanelVentanaLayout.setHorizontalGroup(
            PanelVentanaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PanelVentanaLayout.createSequentialGroup()
                .addContainerGap()
                .add(PanelVentanaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(PanelBanner, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(PanelCuerpo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelVentanaLayout.setVerticalGroup(
            PanelVentanaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PanelVentanaLayout.createSequentialGroup()
                .addContainerGap()
                .add(PanelBanner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(PanelCuerpo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 383, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PanelVentana, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PanelVentana, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
         FondoVentanas p = new FondoVentanas();
         PanelVentana.add(p);           
         PanelVentana.repaint();
         FondoBanner p2 = new FondoBanner();
         PanelBanner.add(p2);           
         PanelBanner.repaint();
    }//GEN-LAST:event_formWindowOpened

    private void BotonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegresarActionPerformed
        ListadoAlumnos la= new ListadoAlumnos (carrera,asignatura,codigo,seccion);
        la.setVisible(true);
        dispose();
    }//GEN-LAST:event_BotonRegresarActionPerformed

    private void BotonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardarActionPerformed
        
        int item=ComboNota.getSelectedIndex();
        try{
            
            if (item==0)
            {
                Mensaje.showMessageDialog(this,"Elija la nota","Error",Mensaje.ERROR_MESSAGE);
            }
            
            else
            {
                
                Mensaje.showMessageDialog(null,"Datos almacenados exitosamente.","Info",Mensaje.INFORMATION_MESSAGE);
                lista_inscritos li=new lista_inscritos();
                li.asignanota(codigo,cedulaalumno,ComboNota.getSelectedItem().toString());
                ListadoAlumnos la= new ListadoAlumnos (carrera,asignatura,codigo,seccion);
                la.setVisible(true);
                dispose();
            }
        
        }catch (IOException ex) {
            System.out.println(ex);
            }catch (ClassNotFoundException ex) {
               System.out.println(ex);
            }
    }//GEN-LAST:event_BotonGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AsignarNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AsignarNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AsignarNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AsignarNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonGuardar;
    private javax.swing.JButton BotonRegresar;
    private javax.swing.JComboBox ComboNota;
    private javax.swing.JLabel EtqApellido;
    private javax.swing.JLabel EtqCarrera;
    private javax.swing.JLabel EtqCedula;
    private javax.swing.JLabel EtqCodigo;
    private javax.swing.JLabel EtqDatosAlumno;
    private javax.swing.JLabel EtqDireccion;
    private javax.swing.JLabel EtqMateria;
    private javax.swing.JLabel EtqNombre;
    private javax.swing.JLabel EtqNota;
    private javax.swing.JLabel EtqSeccion;
    private javax.swing.JOptionPane Mensaje;
    private javax.swing.JPanel PanelBanner;
    private javax.swing.JPanel PanelCuerpo;
    private javax.swing.JPanel PanelVentana;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
